Models/EntradaModel.cs
namespace LEKSupplyApplication.Models
{
    public class EntradaModel
    {
        public int Id { get; set; }

        public int NmrRegistro { get; set; }

        public int Quantidade { get; set; }

        public DateTime Data { get; set; }

        public string Local { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace LEKSupplyApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MercadoriaModel.cs
using System.ComponentModel.DataAnnotations;

namespace LEKSupplyApplication.Models
{
    public class MercadoriaModel
    {
        public int Id { get; set; }

        //Validação dos campo
        [Required(ErrorMessage = "Digite o nome da mercadoria")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Digite o número de registro da mercadoria")]
        public int NmrRegistro { get; set; }

        [Required(ErrorMessage = "Digite o nome do fabricante da mercadoria")]
        public string Fornecedor { get; set; }

        [Required(ErrorMessage = "Digite o tipo da mercadoria")]
        public string Tipo { get; set; }

        [Required(ErrorMessage = "Digite uma descrição para a mercadoria")]
        public string Descricao { get; set; }
    }
}

Models/SaidaModel.cs
namespace LEKSupplyApplication.Models
{
    public class SaidaModel
    {
        public int Id { get; set; }

        public int NmrRegistro { get; set; }

        public int Quantidade { get; set; }

        public DateTime Data { get; set; }

        public string Local { get; set; }
    }
}

Controllers/EntradaController.cs
using Microsoft.AspNetCore.Mvc;

namespace LEKSupplyApplication.Controllers
{
    public class EntradaController : Controller
    {
       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RelatorioEntradas()
        {
            return View();
        }

        public IActionResult CadastrarEntrada()
        {
            return View();
        }

    }
}

Controllers/HomeController.cs
using LEKSupplyApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LEKSupplyApplication.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MercadoriaController.cs
using LEKSupplyApplication.Models;
using LEKSupplyApplication.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace LEKSupplyApplication.Controllers
{
    public class MercadoriaController : Controller
    {
        private readonly InterfaceMercadoriaRepositorio _mercadoriaRepositorio;
        public MercadoriaController(InterfaceMercadoriaRepositorio mercadoriaRepositorio) 
        {
            _mercadoriaRepositorio = mercadoriaRepositorio;
        }
        public IActionResult Index()
        {   
            List<MercadoriaModel> mercadoria = _mercadoriaRepositorio.BuscarTodos();
            return View(mercadoria);
        }

        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            MercadoriaModel mercadoria = _mercadoriaRepositorio.ListarPorId(id);
            return View(mercadoria);
        }

        public IActionResult ApagarConfirmacao()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Adicionar(MercadoriaModel mercadoria)
        {
            try
            {
                //Validação
                if (ModelState.IsValid)
                {
                    _mercadoriaRepositorio.Adicionar(mercadoria);
                    TempData["MensagemSucesso"] = "Mercadoria cadastrada com sucesso";
                    return RedirectToAction("Index");
                }

                return View(mercadoria);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possível cadastrar a sua mercadoria, tente novamente! Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(MercadoriaModel mercadoria)
        {
            try
            {
                //Validação
                if (ModelState.IsValid)
                {
                    _mercadoriaRepositorio.Atualizar(mercadoria);
                    TempData["MensagemSucesso"] = "Mercadoria atualizada com sucesso";
                    return RedirectToAction("Index");
                }

                return View("Editar", mercadoria);
            }
            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possível atualizar a sua mercadoria, tente novamente! Detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

Controllers/SaidaController.cs
using Microsoft.AspNetCore.Mvc;

namespace LEKSupplyApplication.Controllers
{
    public class SaidaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RelatorioSaidas()
        {
            return View();
        }

        public IActionResult CadastrarSaida()
        {
            return View();
        }
    }
}

Views/Entrada/CadastrarEntrada.cshtml
@{
    ViewData["Title"] = "Cadastrar entrada";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar entrada de mercadoria</h1>
</div>

<form>
    //Formulário de adição
</form>

Views/Entrada/Index.cshtml
@model List<MercadoriaModel>

@{
    ViewData["Title"] = "Página de entrada de mercadorias";
}

<div class="text-center">
    <h1 class="display-4">Entrada de mercadorias!</h1>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Entrada" asp-action="RelatorioEntradas">Relatório de entradas</a>
    </div>
    <h2 class="display-4">Lista de mercadorias cadastradas</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Nº de Registro</th>
                <th scope="col">Fabricante</th>
                <th scope="col">Tipo</th>
                <th scope="col">Descrição</th>
                <th scope="col">Quantidade</th>
                <th scope="col">Data</th>
                <th scope="col">Local</th>
                <th scope="col">Entrada</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (MercadoriaModel mercadoria in Model)
                {
                    <tr>
                        <th scope="row">@mercadoria.Id</th>
                        <td>@mercadoria.Nome</td>
                        <td>@mercadoria.NmrRegistro</td>
                        <td>@mercadoria.Fornecedor</td>
                        <td>@mercadoria.Tipo</td>
                        <td>@mercadoria.Descricao</td>
                        <td>@mercadoria</td>
                        <td>@mercadoria</td>
                        <td>@mercadoria</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Exemplo básico">
                                <a role="button" class="btn btn-primary" asp-router-id="@mercadoria.Id" asp-controller="Entrada" asp-action="CadastrarEntrada">Cadastrar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Entrada/RelatorioEntradas.cshtml
@{
    ViewData["Title"] = "Relatório de entrada de mercadorias";
}

<div class="text-center">
    <h1>Relatório de entradas aqui!</h1>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Entrada" asp-action="Index">Voltar</a>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo usuário!</h1>
    <p>Sistema de gerencimaneto de mercadorias - LEKSupply</p>
</div>

Views/Mercadoria/Adicionar.cshtml
@model MercadoriaModel

@{
    ViewData["Title"] = "Adicionar mercadoria";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar mercadoria</h1>
</div>

<form asp-controller="Mercadoria" asp-action="Adicionar" method="post">
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite seu nome">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <br />
    <div class="form-group">
        <label for="numeroDeRegistro">Nº de Registro</label>
        <input type="number" asp-for="NmrRegistro" class="form-control" placeholder="Digite o número do registro">
        @Html.ValidationMessageFor(x => x.NmrRegistro)
    </div>
    <br />
    <div class="form-group">
        <label for="fabricante">Fabricante</label>
        <input type="text" asp-for="Fornecedor" class="form-control" placeholder="Digite o nome do fabricante">
        @Html.ValidationMessageFor(x => x.Fornecedor)
    </div>
    <br />
    <div class="form-group">
        <label for="tipo">Tipo</label>
        <input type="text" asp-for="Tipo" class="form-control" placeholder="Digite o tipo da mercadoria">
        @Html.ValidationMessageFor(x => x.Tipo)
    </div>
    <br />
    <div class="form-group">
        <label for="descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" placeholder="Digite a descrição da mercadoria">
        @Html.ValidationMessageFor(x => x.Descricao)
    </div>
    <br />
    <button type="submit" class="btn btn-primary btn-lg btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-lg btn-block" role="button" asp-controller="Mercadoria" asp-action="Index">Voltar</a>
</form>

Views/Mercadoria/ApagarConfirmacao.cshtml
@{
    ViewData["Title"] = "Confirmação de apagar mercadoria";
}

<div class="text-center">
    <h3 class="display-4">Deseja realmente apagar esta mercadoria?</h3>
</div>
<br />
<a class="btn btn-primary btn-block" role="button" asp-controller="Mercadoria" asp-action="Index">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-controller="Mercadoria" asp-action="Apagar">Confirmar exclusão</a>

Views/Mercadoria/Editar.cshtml
@model MercadoriaModel

@{
    ViewData["Title"] = "Editar mercadoria cadastrada";
}

<div class="text-center">
    <h1 class="display-4">Editar mercadoria</h1>
</div>

<form asp-controller="Mercadoria" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite seu nome">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>
    <br />
    <div class="form-group">
        <label for="numeroDeRegistro">Nº de Registro</label>
        <input type="number" asp-for="NmrRegistro" class="form-control" placeholder="Digite o número do registro">
        @Html.ValidationMessageFor(x => x.NmrRegistro)
    </div>
    <br />
    <div class="form-group">
        <label for="fabricante">Fabricante</label>
        <input type="text" asp-for="Fornecedor" class="form-control" placeholder="Digite o nome do fabricante">
        @Html.ValidationMessageFor(x => x.Fornecedor)
    </div>
    <br />
    <div class="form-group">
        <label for="tipo">Tipo</label>
        <input type="text" asp-for="Tipo" class="form-control" placeholder="Digite o tipo da mercadoria">
        @Html.ValidationMessageFor(x => x.Tipo)
    </div>
    <br />
    <div class="form-group">
        <label for="descricao">Descrição</label>
        <input type="text" asp-for="Descricao" class="form-control" placeholder="Digite a descrição da mercadoria">
        @Html.ValidationMessageFor(x => x.Descricao)
    </div>
    <br />
    <button type="submit" class="btn btn-primary btn-lg btn-block">Alterar</button>
    <a class="btn btn-secondary btn-lg btn-block" role="button" asp-controller="Mercadoria" asp-action="Index">Voltar</a>
</form>

Views/Mercadoria/Index.cshtml
@model List<MercadoriaModel>

@{
    ViewData["Title"] = "Cadastro de mercadorias";
}

<div class="text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Mercadoria" asp-action="Adicionar">Adicionar mercadoria</a>
    </div>
    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemSucesso"]
        </div>
    }
    
    @if (TempData["MensagemErro"] != null)
    { 
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">x</button>
            @TempData["MensagemErro"]
        </div>
    }
  
    <br/>
    <h1 class="display-4">Lista de mercadorias ativas</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Nº de Registro</th>
                <th scope="col">Fabricante</th>
                <th scope="col">Tipo</th>
                <th scope="col">Descrição</th>
                <th scope="col">Ação</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (MercadoriaModel mercadoria in Model)
                {
                    <tr>
                        <th scope="row">@mercadoria.Id</th>
                        <td>@mercadoria.Nome</td>
                        <td>@mercadoria.NmrRegistro</td>
                        <td>@mercadoria.Fornecedor</td>
                        <td>@mercadoria.Tipo</td>
                        <td>@mercadoria.Descricao</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Exemplo básico">
                                <a role="button" class="btn btn-primary" asp-route-id="@mercadoria.Id" asp-controller="Mercadoria" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@mercadoria.Id" asp-controller="Mercadoria" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Saida/CadastrarSaida.cshtml
@{
    ViewData["Title"] = "Cadastrar saída";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar saída de mercadoria</h1>
</div>

<form>
    //Formulário de remoção de mercadorias
</form>

Views/Saida/Index.cshtml
@model List<MercadoriaModel>

@{
    ViewData["Title"] = "Página de saída de mercadorias";
}

<div class="text-center">
    <h1 class="display-4">Saída de mercadorias!</h1>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Saida" asp-action="RelatorioSaidas">Relatório de saídas</a>
    </div>
    <h2 class="display-4">Lista de mercadorias cadastradas</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Nº de Registro</th>
                <th scope="col">Fabricante</th>
                <th scope="col">Tipo</th>
                <th scope="col">Descrição</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (MercadoriaModel mercadoria in Model)
                {
                    <tr>
                        <th scope="row">@mercadoria.Id</th>
                        <td>@mercadoria.Nome</td>
                        <td>@mercadoria.NmrRegistro</td>
                        <td>@mercadoria.Fornecedor</td>
                        <td>@mercadoria.Tipo</td>
                        <td>@mercadoria.Descricao</td>                  
                        <td>
                            <div class="btn-group" role="group" aria-label="Exemplo básico">
                                <a role="button" class="btn btn-primary" asp-router-id="@mercadoria.Id" asp-controller="Saida" asp-action="CadastrarSaida">Cadastrar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

Views/Saida/RelatorioSaidas.cshtml
@{
    ViewData["Title"] = "Relatório de saída de mercadorias";
}

<div class="text-center">
    <h1>Relatório de saídas aqui!</h1>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Saida" asp-action="Index">Voltar</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LEKSupplyApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LEKSupplyApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LEKSupplyApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página principal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mercadoria" asp-action="Index">Cadastro de mercadoria</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Entrada" asp-action="Index">Cadastro de entrada</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Saida" asp-action="Index">Cadastro de saída</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LEKSupplyApplication - Gerenciamento de Mercadorias
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>